wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1682448428.198607
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      4: 3.9.7
      5: 0.15.0
      8:
      - 1
      - 2
      - 3
      - 5
